export const userData=[
    {
        id:"1",
        firstname:"Deepu",
        lastname:"Gupta",
        username:"deepu47",
        address:"Gaya",
        gender:"male",
        status:"inactive",
        password:"deepu123"
    },
    {
        id:"2",
        firstname:"Pooja",
        lastname:"Roy",
        username:"pooja47",
        address:"Gaya",
        gender:"female",
        status:"inactive",
        password:"pooja123"
    },
    {
        id:"3",
        firstname:"Aradhya",
        lastname:"Singh",
        username:"aradhya47",
        address:"Gaya",
        gender:"female",
        status:"active",
        password:"aradhya123"
    },
    {
        id:"4",
        firstname:"Brajesh",
        lastname:"Kumar",
        username:"brajesh47",
        address:"Gaya",
        gender:"male",
        status:"active",
        password:"brajesh123"
    },
    {
        id:"5",
        firstname:"Shilpi",
        lastname:"Bharti",
        username:"shilpi10",
        address:"Gaya",
        gender:"female",
        status:"active",
        password:"deepa123"
    },
    {
        id:"6",
        firstname:"Sunny",
        lastname:"Mehta",
        username:"sunny12",
        address:"Gaya",
        gender:"male",
        status:"inactive",
        password:"sunny123"
    },
    {
        id:"7",
        firstname:"Khushi",
        lastname:"Verma",
        username:"khushi47",
        address:"Gaya",
        gender:"female",
        status:"inactive",
        password:"khushi123"
    },
    {
        id:"8",
        firstname:"Krisha",
        lastname:"Prakash",
        username:"krisha90",
        address:"Aurangabad",
        gender:"female",
        status:"active",
        password:"krisha123"
    },
    {
        id:"9",
        firstname:"Saurav",
        lastname:"Bharti",
        username:"saurav",
        address:"Gaya",
        gender:"male",
        status:"active",
        password:"saurav123"
    },
    {
        id:"10",
        firstname:"Beauty",
        lastname:"Kumari",
        username:"beauty67",
        address:"Gaya",
        gender:"female",
        status:"active",
        password:"beauty123"
    }
]